theme: jekyll-theme-leap-day
title: Tools and techniques to bridge the gap between models and closed-loop neuroscience experiments
description: CNS2020 Closed-Loop Neuroscience Tutorial
show_downloads: false
