theme: jekyll-theme-leap-day
title: CNS 2020 Closed-Loop Neuroscience Tutorial
description: Tools and techniques to bridge the gap between models and closed-loop neuroscience experiments
show_downloads: false
